# Generated by Django 2.1.8 on 2019-06-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190612_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
